<?php
$base = c('modules.api.base');
$export[] = array($base . '/board/:action/:name', array('controller' => 'board', 'module'=>'api', 'action' => null));
$export[] = array($base . '/threads/:name/:id', array('controller' => 'article', 'module'=>'api', 'action' => 'threads'), array('id' => '\d+'));
$export[] = array($base . '/article/:name/:action/:id', array('controller' => 'article', 'module' => 'api', 'action' => null), array('id' => '\d+'));
$export[] = array($base . '/article/:name/:action', array('controller' => 'article', 'module' => 'api'));
$export[] = array($base . '/attachment/:name/:mode/:id/:pos/:type', array('controller' => 'attachment', 'module'=>'api', 'action'=>'download', 'mode' => null, 'type' => null), array('name' => '\w+', 'id' => '\d+', 'pos' => '\d+', 'mode' => '\d+', 'type' => '\w[\w\d-]*'));
$export[] = array($base . '/attachment/:name/:action/:id', array('controller' => 'attachment', 'module' => 'api', 'action' => null, 'id' => null), array('id' => '\d+'));
$export[] = array($base . '/user/:action/:id', array('controller' => 'user', 'module' => 'api', 'id' => null), array('id' => '\w+'));
$export[] = array($base . '/section', array('controller' => 'section', 'module'=>'api', 'action' => 'root'));
$export[] = array($base . '/section/:name', array('controller' => 'section', 'module' => 'api', 'action' => 'index'));
$export[] = array($base . '/mail/send', array('controller' => 'mail', 'module' => 'api', 'action' => 'send'));
$export[] = array($base . '/mail/info', array('controller' => 'mail', 'module' => 'api', 'action' => 'info'));
$export[] = array($base . '/mail/:type/:action/:num', array('controller' => 'mail', 'module' => 'api', 'action' => null), array('num' => '\d+'));
$export[] = array($base . '/mail/:type', array('controller' => 'mail', 'module' => 'api', 'action' => 'box'));
$export[] = array($base . '/widget/:name', array('controller' => 'widget', 'module' => 'api', 'action' => 'index'));
$export[] = array($base . '/search/:action', array('controller' => 'search', 'module' => 'api'));
$export[] = array($base . '/favorite/:action/:num', array('controller' => 'favorite', 'module' => 'api', 'action' => null), array('num' => '\d+'));
$export[] = array($base . '/refer/:type/:action/:index', array('controller' => 'refer', 'module' => 'api', 'action' => null, 'index' => null), array('index' => '\d+'));
$export[] = array($base . '/vote/:action/:id', array('controller' => 'vote', 'module' => 'api', 'action' => null), array('id' => '\w+'));
$export[] = array($base . '/blacklist/:action', array('controller' => 'blacklist', 'module' => 'api', 'action' => null));
$export[] = array($base . '/*', array('controller' => 'error', 'module' => 'api', 'action' => 'error'), array(), false);
